name: myfundsuthm
description: Fundraising System for student in UTHM

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.8.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+1
  equatable: ^2.0.3
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_storage: ^11.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^2.0.6
  google_fonts: ^4.0.4
  intl: ^0.18.1
  line_awesome_flutter: ^2.0.0
  lottie: ^2.4.0
  percent_indicator: ^4.2.2
  platform: ^3.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/icon/1024.png"
  adaptive_icon_foreground: "assets/icon/1024.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

